export { 
  createEvent,
  getEvents,
  updateEvent,
  deleteEvent,
  createMeetup,
  getMeetups,
  updateMeetup,
  deleteMeetup,
  createUser,
  getUsers,
  updateUser,
  deleteUser,
  createBooking,
  getUserBookings,
  updateBookingStatus,
  fetchPaymentCards,
  createPaymentCard,
  updatePaymentCard,
  deletePaymentCard,
  setDefaultPaymentCard,
  fetchFavorites,
  addFavorite,
  deleteFavorite,
  fetchUserProfile,
  updateUserProfile,
  fetchUserStats,
  // Unified service functions
  getAllItems,
  getItemById
} from './dataService';

export type { 
  Event, 
  Meetup, 
  User,
  Booking,
  Favorite,
  PaymentMethod,
  UnifiedItem,
  UnifiedItemProperties,
  AuthProvider,
  UserProfile,
  BookingFormData
} from '@/utils/schemas';
